[project]
name = "niceterminal"
version = "0.1.0"
description = "A library for building terminal applications with NiceGUI and rich terminal features."
authors = [
    {name = "Aki Mimoto", email = "aki@bako.ca"},
]
dependencies = [
    "nicegui>=2.5.0",
    "pyte>=0.8.2",
    "invoke>=2.1.3",
    "pywinpty>=2.0.4; platform_system == 'Windows'",
    "loguru>=0.7.2",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT-0"}

[tool.pdm]
distribution = true
build = { includes = ["src/niceterminal"] }

[build-system]
requires = ["pdm-backend>=0.12"]
build-backend = "pdm.backend"


